version: "3"


services:
  nfs:
    container_name: nfs-service
    image: itsthenetwork/nfs-server-alpine:latest
    network_mode: "bridge"
    privileged: true
    ports:
      - "2049:2049/tcp"
    #  - "111:111/tcp"
    #  - "111:111/udp"
    environment:
      - TZ='America/Chicago'
      - SHARED_DIRECTORY=/nfsshare
    volumes:
      - /big/share:/nfsshare
      - /home/lkaut/compose/nfs-server/exports:/etc/exports
    cap_add:
      - SYS_ADMIN
    #  - SETPCAP
    restart: unless-stopped
